//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistrictsNew.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DistrictsNew.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карточка с таким именем уже существует.
        /// </summary>
        public static string AddCard_AlreadyExisting {
            get {
                return ResourceManager.GetString("AddCard_AlreadyExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите имя карточки.
        /// </summary>
        public static string AddCard_EnterCardName {
            get {
                return ResourceManager.GetString("AddCard_EnterCardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждаю.
        /// </summary>
        public static string AS_Confirm {
            get {
                return ResourceManager.GetString("AS_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление записи может ошибочно стереть историю ведения карточки.
        ///Подтвердить вменяемость?.
        /// </summary>
        public static string AS_DeleteRecordConfirmation {
            get {
                return ResourceManager.GetString("AS_DeleteRecordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите дату.
        /// </summary>
        public static string AS_EnterDate {
            get {
                return ResourceManager.GetString("AS_EnterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите имя .
        /// </summary>
        public static string AS_EnterName {
            get {
                return ResourceManager.GetString("AS_EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр:.
        /// </summary>
        public static string AS_Filter {
            get {
                return ResourceManager.GetString("AS_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действия.
        /// </summary>
        public static string Main_Menu_Actions {
            get {
                return ResourceManager.GetString("Main_Menu_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действие.
        /// </summary>
        public static string Manage_Action {
            get {
                return ResourceManager.GetString("Manage_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все.
        /// </summary>
        public static string Manage_All {
            get {
                return ResourceManager.GetString("Manage_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя карточки.
        /// </summary>
        public static string Manage_CardName {
            get {
                return ResourceManager.GetString("Manage_CardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string Manage_Date {
            get {
                return ResourceManager.GetString("Manage_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последний владелец.
        /// </summary>
        public static string Manage_LastOwner {
            get {
                return ResourceManager.GetString("Manage_LastOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата сдачи.
        /// </summary>
        public static string Manage_LastPassDate {
            get {
                return ResourceManager.GetString("Manage_LastPassDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата выдачи на руки.
        /// </summary>
        public static string Manage_LastTaskeDate {
            get {
                return ResourceManager.GetString("Manage_LastTaskeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Утерян.
        /// </summary>
        public static string Manage_Lost {
            get {
                return ResourceManager.GetString("Manage_Lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не на руках.
        /// </summary>
        public static string Manage_NotOnHands {
            get {
                return ResourceManager.GetString("Manage_NotOnHands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брали более 3 месяцев назад.
        /// </summary>
        public static string Manage_NotOnHands3 {
            get {
                return ResourceManager.GetString("Manage_NotOnHands3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брали более полугода назад.
        /// </summary>
        public static string Manage_NotOnHands6 {
            get {
                return ResourceManager.GetString("Manage_NotOnHands6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брали более года назад.
        /// </summary>
        public static string Manage_NotOnHandsYear {
            get {
                return ResourceManager.GetString("Manage_NotOnHandsYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На руках более 3 месяцев.
        /// </summary>
        public static string Manage_OnHandMore3 {
            get {
                return ResourceManager.GetString("Manage_OnHandMore3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На руках более полугода.
        /// </summary>
        public static string Manage_OnHandMore6 {
            get {
                return ResourceManager.GetString("Manage_OnHandMore6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На руках более года.
        /// </summary>
        public static string Manage_OnHandMoreYear {
            get {
                return ResourceManager.GetString("Manage_OnHandMoreYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На руках.
        /// </summary>
        public static string Manage_OnHands {
            get {
                return ResourceManager.GetString("Manage_OnHands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ответственный.
        /// </summary>
        public static string Manage_Owner {
            get {
                return ResourceManager.GetString("Manage_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сдан.
        /// </summary>
        public static string Manage_Passed {
            get {
                return ResourceManager.GetString("Manage_Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Взят.
        /// </summary>
        public static string Manage_Taken {
            get {
                return ResourceManager.GetString("Manage_Taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ведение участков.
        /// </summary>
        public static string Manage_Title {
            get {
                return ResourceManager.GetString("Manage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string Settings_Add {
            get {
                return ResourceManager.GetString("Settings_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите имя улицы.
        /// </summary>
        public static string Settings_EnterStreetName {
            get {
                return ResourceManager.GetString("Settings_EnterStreetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во квартир на карточке.
        /// </summary>
        public static string Settings_RoomsCount {
            get {
                return ResourceManager.GetString("Settings_RoomsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список улиц.
        /// </summary>
        public static string Settings_StreetList {
            get {
                return ResourceManager.GetString("Settings_StreetList", resourceCulture);
            }
        }
    }
}
